const Data = [
    {
        id: 1,
        Q: 'what is your name?',
        A:'santan',
        B: 'sayantan',
        C: 'sayantananan',
        D: 'sayantannd',
    },
    {
        id: 2,
        Q: 'what is your current location?',
        A:'mumbai',
        B: 'pune',
        C: 'hyderabad',
        D: 'kolkata',
    },
    {
        id: 3,
        Q: 'what is your pass out year of degree course?',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },
    {
        id: 4,
        Q: 'What is computer network?',
        A:'security',
        B: 'both hardware & software',
        C: 'hardware',
        D: 'software',
    },{
        id: 5,
        Q: 'A Process is a ____________.',
        A: 'system',
        B: 'algorithm',
        C: 'Step by step',
        D: 'networking method',
    },{
        id: 6,
        Q: 'What is smallest unit of the information?',
        A: 'data',
        B: 'integer',
        C: 'string',
        D: 'boolean',
    },{
        id: 7,
        Q: 'How many color dots make up one color pixel on a screen?',
        A:  '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 8,
        Q: 'How is the data stored on the diskette?',
        A: 'series',
        B: 'parallel',
        C: 'magnetic',
        D: 'ic based',
    },{
        id: 9,
        Q: 'which of the following is the smallest visual element on a video monitor?',
        A: 'led monitor',
        B: 'smart tv',
        C: 'FHD monitor',
        D: 'tablet',
    },{
        id: 10,
        Q: 'which of the following is an output device?',
        A: 'mouse',
        B: 'printer',
        C: 'RAM',
        D: 'SSD',
    },{
        id: 11,
        Q: 'which of the following is an input device?',
        A: 'mouse',
        B: 'printer',
        C: 'keyboard',
        D: 'Processor',
    },{
        id: 12,
        Q: 'which of the following is the extension of Notepad?',
        A: 'C++',
        B: 'wordpad',
        C: 'onenote',
        D: 'ms-word',
    },{
        id: 13,
        Q: 'BIOS is used?',
        A: 'control hardware',
        B: 'windows',
        C: 'DOS',
        D: 'LINUX',
    },{
        id: 14,
        Q: 'A computer is accurate, but if the result of a computation is false, what is the main reason for it?',
        A: 'trial error',
        B: 'boot error',
        C: 'mother board problem',
        D: 'OS problem',
    },{
        id: 15,
        Q: 'which kind of language can computer understand?',
        A: 'assembly language',
        B: 'High language',
        C: 'Machine language',
        D: 'low language',
    },{
        id: 16,
        Q: 'what is the full form of RAM',
        A: 'Read Acess memory',
        B: 'Read Alternative Memory',
        C: 'Random Access Memory',
        D: 'Random Alternative Memory',
    },{
        id: 17,
        Q: 'what is the full form of DRAM',
        A: 'Data Random Access Memory',
        B: 'Data Random Active Memory',
        C: 'Dynamic Random Access Memory',
        D: 'Double Random Access Memory',
    },{
        id: 18,
        Q: 'Which one of the following software applications would be the most appropriate for performing numerical and statistical calculations?',
        A: 'Database',
        B: 'Document processor',
        C: 'Graphics package',
        D: 'Spreadsheet',
    },{
        id: 19,
        Q: 'Which of the following is not considered hardware?',
        A: 'Operating system',
        B: 'CPU',
        C: 'Keyboard',
        D: 'Hard disk',
    },{
        id: 20,
        Q: 'What is the full form of USB?',
        A: 'universal serial bus',
        B: 'universal security block',
        C: 'universal serial bus',
        D: 'ultra security board',
    },{
        id: 21,
        Q: 'Which one of the following is not a form of data storage media?',
        A: 'database',
        B: 'magnetic tape',
        C: 'magnetic disc',
        D: 'optical disk',
    },{
        id: 22,
        Q: 'Which of the following would be the correct description for WORM virus?',
        A: 'It infects the boot sector.',
        B: 'It propagates through the internet and e-mail.',
        C: 'It has no effect in increasing the internet traffic.',
        D: 'It alters the folder structure.',
    },{
        id: 23,
        Q: 'The use of the IC in a computer has ______.',
        A: 'Increased the amount of heating ',
        B: 'Reduced the size and cost of computers',
        C: 'Reduced the peripheral devices to be used',
        D: 'Reduced the performance capacity of the computer',
    },{
        id: 24,
        Q: 'Properly arranged data is known as',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 25,
        Q: 'Which of the following can access the server?',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 26,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 27,
        Q: 'Which of the following is created when a user opens an account in the computer system?',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 28,
        Q: 'Which of the following type of computer is mostly used for automatic operations?',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 29,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 30,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 31,
        Q: 'Which of the following is the first neural network computer?',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 32,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 33,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 34,
        Q: 'The time that depends on the input: an already sorted sequence that is easier to sort.',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 35,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 36,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 37,
        Q: 'When an algorithm is written in the form of a programming language, it becomes a _________',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 38,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 39,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 40,
        Q: 'A data structure that follows the FIFO principle.',
        A: 'Stack',
        B: 'Queue',
        C: 'Linked List',
        D: 'Array',
    },{
        id: 41,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 42,
        Q: 'Keep the statement language ______________ while writing a pseudo code.',
        A: 'English',
        B: 'bengali',
        C: 'urdu',
        D: 'frech',
    },{
        id: 43,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 44,
        Q: 'Which of the following is not a keyword?',
        A: 'int',
        B: 'float',
        C: 'boolean',
        D: 'str',
    },{
        id: 45,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 46,
        Q: ' ______________ is used to show hierarchy in a pseudo code.',
        A: 'indentation',
        B: 'Curly Braces',
        C: 'Round Brackets',
        D: 'Semicolon',
    },{
        id: 47,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 48,
        Q: 'The statement that tells the computer to get a value from an input device and store it in a memory location.',
        A: 'read',
        B: 'write',
        C: 'READ',
        D: 'WRITE',
    },{
        id: 49,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 50,
        Q: '____________ begins with lower case letters.',
        A: 'keywords',
        B: 'variables',
        C: 'tokens',
        D: 'functions',
    },{
        id: 51,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 52,
        Q: 'Another notation for exponentiation',
        A: '*',
        B: '**',
        C: '***',
        D: '*^',
    },{
        id: 53,
        Q: 'Ques',
        A: '2022',
        B: '2018',
        C: '2020',
        D: '2010',
    },{
        id: 54,
        Q: 'A symbol used for grouping.',
        A: '()',
        B: '{}',
        C: '[]',
        D: '""',
    },
]

export default Data;